// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

    static FirebaseOptions get web => FirebaseOptions(
      apiKey: dotenv.env['WEB_API_KEY']!,
      appId: '1:1049660220815:web:8b109952065c3a1124d7fa',
      messagingSenderId: '1049660220815',
      projectId: 'e-commerce-app-2cf83',
      authDomain: 'e-commerce-app-2cf83.firebaseapp.com',
      storageBucket: 'e-commerce-app-2cf83.firebasestorage.app',
      measurementId: 'G-FS0CX8VFS0',
    );

    static FirebaseOptions get android => FirebaseOptions(
      apiKey: dotenv.env['ANDROID_API_KEY']!,
      appId: '1:1049660220815:android:380ddd105cefb40d24d7fa',
      messagingSenderId: '1049660220815',
      projectId: 'e-commerce-app-2cf83',
      storageBucket: 'e-commerce-app-2cf83.firebasestorage.app',
    );

    static FirebaseOptions get ios => FirebaseOptions(
      apiKey: dotenv.env['IOS_API_KEY']!,
      appId: '1:1049660220815:ios:6b5452a860170e4524d7fa',
      messagingSenderId: '1049660220815',
      projectId: 'e-commerce-app-2cf83',
      storageBucket: 'e-commerce-app-2cf83.firebasestorage.app',
      iosBundleId: 'org.Maheresio.eCommerce',
    );

    static FirebaseOptions get macos => FirebaseOptions(
      apiKey: dotenv.env['MACOS_API_KEY']!,
      appId: '1:1049660220815:ios:6b5452a860170e4524d7fa',
      messagingSenderId: '1049660220815',
      projectId: 'e-commerce-app-2cf83',
      storageBucket: 'e-commerce-app-2cf83.firebasestorage.app',
      iosBundleId: 'org.Maheresio.eCommerce',
    );

    static FirebaseOptions get windows => FirebaseOptions(
      apiKey: dotenv.env['WINDOWS_API_KEY']!,
      appId: '1:1049660220815:web:3ea9432b0d781a6224d7fa',
      messagingSenderId: '1049660220815',
      projectId: 'e-commerce-app-2cf83',
      authDomain: 'e-commerce-app-2cf83.firebaseapp.com',
      storageBucket: 'e-commerce-app-2cf83.firebasestorage.app',
      measurementId: 'G-LHFNFM9DVC',
    );
}
